#Requires -Version 5.1
<#
.SYNOPSIS
    Generates an Android signing keystore for release builds.
.DESCRIPTION
    Creates a release keystore with a cryptographically secure password.
    Output directory and filenames are configured in scripts/settings.json.
    Never commit the signing directory.
.EXAMPLE
    .\Generate-AndroidSigningKey.ps1
.EXAMPLE
    .\Generate-AndroidSigningKey.ps1 -Force
    Overwrites existing keystore and credentials without prompting.
#>

[CmdletBinding()]
param(
    [switch]$UpdateBase64Only,  # Add base64 to existing credentials without regenerating keystore
    [switch]$Force              # Overwrite existing keystore and credentials without prompting
)

$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'AndroidSigningSettings.ps1')
$settings = Get-AndroidSigningSettings

$SigningDir = $settings.SigningDirPath
$KeystorePath = $settings.KeystorePath
$CredentialsPath = $settings.CredentialsPath
$KeyAlias = $settings.KeyAlias
$KeyAlg = $settings.KeyAlgorithm
$KeySize = $settings.KeySize
$ValidityDays = $settings.ValidityDays
$PasswordLength = $settings.PasswordLength

function Find-Keytool {
    $candidates = @()
    if ($env:JAVA_HOME) {
        $candidates += Join-Path $env:JAVA_HOME 'bin\keytool.exe'
    }
    if ($env:ANDROID_HOME) {
        $candidates += Join-Path $env:ANDROID_HOME 'jre\bin\keytool.exe'
        $candidates += Join-Path $env:ANDROID_HOME '..\jre\bin\keytool.exe'
    }
    $studioPaths = @(
        "${env:ProgramFiles}\Android\Android Studio\jbr\bin\keytool.exe",
        "${env:ProgramFiles}\Android\Android Studio\jre\bin\keytool.exe",
        "${env:ProgramFiles(x86)}\Android\Android Studio\jbr\bin\keytool.exe"
    )
    $candidates += $studioPaths
    $openJdkDir = Join-Path ${env:ProgramFiles} 'Android\openjdk'
    if (Test-Path $openJdkDir) {
        $found = Get-ChildItem -Path $openJdkDir -Recurse -Filter 'keytool.exe' -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($found) { $candidates += $found.FullName }
    }
    foreach ($p in $candidates) {
        if ($p -and (Test-Path -LiteralPath $p -ErrorAction SilentlyContinue)) {
            return $p
        }
    }
    $inPath = Get-Command keytool -ErrorAction SilentlyContinue
    if ($inPath) { return $inPath.Source }
    throw "keytool not found. Set JAVA_HOME or install Android Studio JDK."
}

function New-SecurePassword {
    $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%&*'
    $bytes = [byte[]]::new($PasswordLength)
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $sb = [System.Text.StringBuilder]::new($PasswordLength)
    for ($i = 0; $i -lt $PasswordLength; $i++) {
        [void]$sb.Append($chars[$bytes[$i] % $chars.Length])
    }
    return $sb.ToString()
}

function Write-CredentialsFile {
    param([string]$Password, [string]$Alias, [string]$Base64)
    if (Test-Path $CredentialsPath) {
        try {
            $acl = Get-Acl $CredentialsPath
            $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
                $env:USERNAME, 'FullControl', 'Allow'
            )
            $acl.AddAccessRule($rule)
            $acl | Set-Acl $CredentialsPath
        } catch {
            $icacls = Get-Command icacls -ErrorAction SilentlyContinue
            if ($icacls) {
                & icacls $CredentialsPath /grant "${env:USERNAME}:F" 2>$null
            }
            try {
                Remove-Item -LiteralPath $CredentialsPath -Force -ErrorAction Stop
            } catch {
                Write-Warning "Could not reset credentials file permissions. Run: icacls `"$CredentialsPath`" /grant ${env:USERNAME}:F"
            }
        }
    }
    $content = @"
# Android signing credentials - DO NOT COMMIT
# Generated by Generate-AndroidSigningKey.ps1

ANDROID_KEY_ALIAS=$Alias
ANDROID_KEYSTORE_PASSWORD=$Password
ANDROID_KEYSTORE_BASE64=$Base64
"@
    [System.IO.File]::WriteAllText($CredentialsPath, $content, [System.Text.UTF8Encoding]::new($false))
    try {
        $acl = Get-Acl $CredentialsPath
        $acl.SetAccessRuleProtection($true, $false)
        $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
            $env:USERNAME, 'Read', 'Allow'
        )
        $acl.SetAccessRule($rule)
        $acl | Set-Acl $CredentialsPath
    } catch {
        Write-Warning "Could not restrict credentials file permissions: $_"
    }
}

try {
    if ($UpdateBase64Only) {
        if (-not (Test-Path $KeystorePath)) {
            throw "Keystore not found at $KeystorePath. Run without -UpdateBase64Only to create it."
        }
        $creds = Get-Content $CredentialsPath -Raw
        if ($creds -match 'ANDROID_KEYSTORE_BASE64=') {
            Write-Host "ANDROID_KEYSTORE_BASE64 already in credentials. Replacing..." -ForegroundColor Yellow
            $creds = $creds -replace 'ANDROID_KEYSTORE_BASE64=.*', ''
            $creds = $creds.TrimEnd()
        }
        $base64 = [System.Convert]::ToBase64String([System.IO.File]::ReadAllBytes($KeystorePath))
        $creds += "`nANDROID_KEYSTORE_BASE64=$base64"
        [System.IO.File]::WriteAllText($CredentialsPath, $creds, [System.Text.UTF8Encoding]::new($false))
        Write-Host "Added ANDROID_KEYSTORE_BASE64 to $CredentialsPath" -ForegroundColor Green
        exit 0
    }

    Write-Host "Resolving keytool..." -ForegroundColor Cyan
    $keytool = Find-Keytool
    Write-Host "  Found: $keytool" -ForegroundColor Green

    if (Test-Path $KeystorePath) {
        if ($Force) {
            Write-Host "Overwriting existing keystore at $KeystorePath" -ForegroundColor Yellow
            Remove-Item -LiteralPath $KeystorePath -Force
            if (Test-Path $CredentialsPath) {
                try {
                    Remove-Item -LiteralPath $CredentialsPath -Force
                } catch {
                    & icacls $CredentialsPath /grant "${env:USERNAME}:F" 2>$null
                    Remove-Item -LiteralPath $CredentialsPath -Force -ErrorAction SilentlyContinue
                }
            }
        } else {
            Write-Warning "Keystore already exists at $KeystorePath"
            $confirm = Read-Host "Overwrite? (y/N)"
            if ($confirm -ne 'y' -and $confirm -ne 'Y') {
                Write-Host "Aborted."
                exit 0
            }
            Remove-Item -LiteralPath $KeystorePath -Force
            if (Test-Path $CredentialsPath) {
                try {
                    Remove-Item -LiteralPath $CredentialsPath -Force
                } catch {
                    & icacls $CredentialsPath /grant "${env:USERNAME}:F" 2>$null
                    Remove-Item -LiteralPath $CredentialsPath -Force -ErrorAction SilentlyContinue
                }
            }
        }
    }

    [void](New-Item -ItemType Directory -Path $SigningDir -Force)
    $password = New-SecurePassword

    $dname = Get-CertificateDnameString -Dname $settings.CertificateDname
    Write-Host "Creating keystore..." -ForegroundColor Cyan
    & $keytool -genkeypair -v `
        -keystore $KeystorePath `
        -alias $KeyAlias `
        -keyalg $KeyAlg `
        -keysize $KeySize `
        -validity $ValidityDays `
        -storepass $password `
        -keypass $password `
        -dname $dname

    if (-not (Test-Path $KeystorePath)) {
        throw "Keystore was not created."
    }

    Write-Host "`nValidating keystore..." -ForegroundColor Cyan
    & $keytool -list -keystore $KeystorePath -storepass $password | Out-Null
    Write-Host "  Keystore validated successfully." -ForegroundColor Green

    $keystoreBytes = [System.IO.File]::ReadAllBytes($KeystorePath)
    $base64 = [System.Convert]::ToBase64String($keystoreBytes)
    Write-CredentialsFile -Password $password -Alias $KeyAlias -Base64 $base64

    Write-Host "`n=== GitHub Secrets ===" -ForegroundColor Yellow
    Write-Host "Add these to your repository secrets (Settings > Secrets and variables > Actions):`n"
    Write-Host "ANDROID_KEY_ALIAS"
    Write-Host "  Value: $KeyAlias`n"
    Write-Host "ANDROID_KEYSTORE_PASSWORD"
    Write-Host "  Value: (stored in $CredentialsPath - do not share)`n"
    Write-Host "ANDROID_KEYSTORE_BASE64"
    Write-Host "  Value: (stored in $CredentialsPath - do not share)`n"
    Write-Host "`nOutput written to:"
    Write-Host "  Keystore:  $KeystorePath"
    Write-Host "  Credentials: $CredentialsPath"
    Write-Host "`nDone. Keep $SigningDir secure and never commit it." -ForegroundColor Green
} catch {
    Write-Error $_
    exit 1
}
